### ISSUE TITLE
Is this still being worked on?

### ISSUE THREAD

**Issue by Gorthezar** [victorscopel/wow-token-converter#1]
Just wondering I noticed you mentioned it doesn't work with the new store.

**Comment by victorscopel** [comment]
I'm still working on it

I kind fixed the script but i'm having a problem to make it work in every page, i'll try to make it work this weekend, i'll post updates soon

**Comment by victorscopel** [comment]
Ok, i just released the new code but it only works with the frontpage, still trying to figure it out how to make it work in everypage, also it works with firefox now
